[workspace]
resolver = "2"
members = ["bin/*", "lib/*"]
default-members = ["bin/*", "lib/*"]

[workspace.package]
authors = ["Lake Armitage <gillyobeast@gmail.com"]
edition = "2021"
rust-version = "1.80"

[workspace.dependencies]
wiremock = "0.5"

